### ISSUE TITLE
Remove "final" property from Aerospike Class

### ISSUE THREAD

**Issue by cpats007** [sergeyklay/aerospike-php-stubs#13]
Hi. I'm wondering if you can remove the final property from the Aerospike stub please as I'm unable to mock it for testing:

`PHPUnit_Framework_Exception: Class "Aerospike" is declared "final" and cannot be mocked.`

Thanks

**Comment by sergeyklay** [comment]
https://github.com/sergeyklay/aerospike-php-stubs/issues/8
