### ISSUE TITLE
Aerospike declared 'final' cannot be mocked

### ISSUE THREAD

**Issue by cpats007** [sergeyklay/aerospike-php-stubs#8]
Hi. Would it be possible to not declare the Aerospike class as final - in this instance I am unable to mock the Aerospike class when writing Unit Tests for a service which uses the class.

Great stub otherwise

Thanks :)

**Comment by sergeyklay** [comment]
Hi! I just tried to make an identical stub class. Original Aerospike class declared as final. Why you mock stub?

**Comment by cpats007** [comment]
I’m writing Unit Tests for methods which interface with Aerospike but I want to mock the results returned from Aerospike as you would normally.

In order to achieve the same with PDO for example, I can mock the PDO object and get it to return specific results on calls within the function

**Comment by sergeyklay** [comment]
Let me understand.. if you will change Aerospike stub and remove `final` statement, you will able to mock Aerospike class without issues?

**Comment by cpats007** [comment]
No, I did try that so I think this must be related to the Aerospike Client itself rather than your stub - I’m talking to Aerospike now about it.

Thanks

**Comment by sergeyklay** [comment]
This issue can be closed?

**Comment by cpats007** [comment]
## Yes, sorry. Thanks

I'm mobile with my Galaxy S4!!

Sent with AquaMail for Android
http://www.aqua-mail.com
